version: 2

updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'weekly'
      assignees:
          - 'bgoonz'
      versioning-strategy: 'lockfile-only'
      pull-request-branch-name:
          separator: '-'
